version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/mnt/root
    privileged: true
    network_mode: host
    environment:
      - DB_PASSWORD=ghp_1234567890abcdefghijklmnopqrstuvwxyz
      - API_SECRET=changeme

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
